bump AGP to D-alpha09. It's actually causing build failure...
It is for reporting reproducible build issue on google issuetracker.

> undefined reference to `dl_iterate_phdr'